name: Generate ASCII Artwork - Multijobs

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay program
              run: |
                sudo apt-get install cowsay -y
                cowsay -f dragon "Run for cover, I am a DRAGON ... RAWR" >> dragon.txt

            - name: Upload Dragon text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file

            - name: Tests Cowsay
              run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [build_job_1, test_job_2]
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon text file
            uses: actions/download-artifact@v4
            with:
              name: dragon-text-file

          - name: Deploy Cowsay
            run: |
              cat dragon.txt
              echo Deploying ... ...
